#spring:
#  jpa:
#    database: mysql
#    show-sql: true
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        type: trace

multitenancy:
  mtapp:
    master:
      datasource:
        url: jdbc:postgresql://localhost:5432/masterdb
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver
        connectionTimeout: 20000
        maxPoolSize: 250
        idleTimeout: 300000
        minIdle: 5
        poolName: masterdb-connection-pool

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect